name: Your Workflow

on:
  push:
    branches:
      - master

jobs:
  check_and_send_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Check if push is from a specific owner
        if: github.repository_owner == github.event.sender.login
        run: |
          echo "Push is from the expected owner. Proceed with the workflow."
